#include<stdio.h>
int main()
{
    int a1,b1,c1,a2,b2,c2,n=0;
    scanf("%d%d%d%d%d%d",&a1,&b1,&c1,&a2,&b2,&c2);
    while(!(a1==a2&&b1==b2&&c1==c2))
    {
        switch(b1)
        {
            case 1:case 3:case 5:case 7:case 8:case 10:
            {
                if(c1<31)c1++;
                else
                {
                    c1=1;
                    b1++;
                }
                n++;
                break;
            }
            case 4:case 6:case 9:case 11:
            {
                if(c1<30)c1++;
                else
                {
                    c1=1;
                    b1++;
                }
                n++;
                break;
            }
            case 2:
            {
                if((a1%4==0&&a1%100!=0)||a1%400==0)
                {
                    if(c1<29)c1++;
                    else
                    {
                        c1=1;
                        b1++;
                    }
                }
                else
                {
                    if(c1<28)c1++;
                    else
                    {
                        c1=1;
                        b1++;
                    }
                }
                n++;
                break;
            }
            default:
            {
                if(c1<31)c1++;
                else
                {
                    c1=1;
                    b1=1;
                    a1++;
                }
                n++;
                break;
            }
        }
    }
    printf("采集时间为%d天",n);
    return 0;
}