package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStatusFile<M extends BaseStatusFile<M>> extends Model<M> implements IBean {

	public M setStatusId(java.lang.Integer statusId) {
		set("statusId", statusId);
		return (M)this;
	}
	
	public java.lang.Integer getStatusId() {
		return getInt("statusId");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

}
