package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRequest<M extends BaseRequest<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setTargetId(java.lang.String targetId) {
		set("targetId", targetId);
		return (M)this;
	}
	
	public java.lang.String getTargetId() {
		return getStr("targetId");
	}

	public M setIsAnswered(java.lang.Integer isAnswered) {
		set("isAnswered", isAnswered);
		return (M)this;
	}
	
	public java.lang.Integer getIsAnswered() {
		return getInt("isAnswered");
	}

	public M setIsAccept(java.lang.Integer isAccept) {
		set("isAccept", isAccept);
		return (M)this;
	}
	
	public java.lang.Integer getIsAccept() {
		return getInt("isAccept");
	}

}
