package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDorm<M extends BaseDorm<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setDormId(java.lang.String dormId) {
		set("dormId", dormId);
		return (M)this;
	}
	
	public java.lang.String getDormId() {
		return getStr("dormId");
	}

	public M setEnrollYear(java.lang.String enrollYear) {
		set("enrollYear", enrollYear);
		return (M)this;
	}
	
	public java.lang.String getEnrollYear() {
		return getStr("enrollYear");
	}

}
