package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseToken<M extends BaseToken<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
		return (M)this;
	}
	
	public java.lang.String getAccessToken() {
		return getStr("access_token");
	}

}
