package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTestCase<M extends BaseTestCase<M>> extends Model<M> implements IBean {

	public M setTestCaseId(java.lang.Integer testCaseId) {
		set("testCaseId", testCaseId);
		return (M)this;
	}
	
	public java.lang.Integer getTestCaseId() {
		return getInt("testCaseId");
	}

	public M setQuestionId(java.lang.Integer questionId) {
		set("questionId", questionId);
		return (M)this;
	}
	
	public java.lang.Integer getQuestionId() {
		return getInt("questionId");
	}

	public M setTestCaseContent(java.lang.String testCaseContent) {
		set("testCaseContent", testCaseContent);
		return (M)this;
	}
	
	public java.lang.String getTestCaseContent() {
		return getStr("testCaseContent");
	}

	public M setAnswer(java.lang.String answer) {
		set("answer", answer);
		return (M)this;
	}
	
	public java.lang.String getAnswer() {
		return getStr("answer");
	}

}
