package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAction<M extends BaseAction<M>> extends Model<M> implements IBean {

	public M setActionId(java.lang.Integer actionId) {
		set("actionId", actionId);
		return (M)this;
	}
	
	public java.lang.Integer getActionId() {
		return getInt("actionId");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setActionCode(java.lang.String actionCode) {
		set("actionCode", actionCode);
		return (M)this;
	}
	
	public java.lang.String getActionCode() {
		return getStr("actionCode");
	}

	public M setActionName(java.lang.String actionName) {
		set("actionName", actionName);
		return (M)this;
	}
	
	public java.lang.String getActionName() {
		return getStr("actionName");
	}

	public M setObjName(java.lang.String objName) {
		set("objName", objName);
		return (M)this;
	}
	
	public java.lang.String getObjName() {
		return getStr("objName");
	}

	public M setClassId(java.lang.String classId) {
		set("classId", classId);
		return (M)this;
	}
	
	public java.lang.String getClassId() {
		return getStr("classId");
	}

}
