package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSimilarity<M extends BaseSimilarity<M>> extends Model<M> implements IBean {

	public M setUserId1(java.lang.String userId1) {
		set("userId1", userId1);
		return (M)this;
	}
	
	public java.lang.String getUserId1() {
		return getStr("userId1");
	}

	public M setUserId2(java.lang.String userId2) {
		set("userId2", userId2);
		return (M)this;
	}
	
	public java.lang.String getUserId2() {
		return getStr("userId2");
	}

	public M setQuestionId(java.lang.Integer questionId) {
		set("questionId", questionId);
		return (M)this;
	}
	
	public java.lang.Integer getQuestionId() {
		return getInt("questionId");
	}

	public M setFromSimilarity(java.lang.Integer fromSimilarity) {
		set("fromSimilarity", fromSimilarity);
		return (M)this;
	}
	
	public java.lang.Integer getFromSimilarity() {
		return getInt("fromSimilarity");
	}

	public M setToSimilarity(java.lang.Integer toSimilarity) {
		set("toSimilarity", toSimilarity);
		return (M)this;
	}
	
	public java.lang.Integer getToSimilarity() {
		return getInt("toSimilarity");
	}

}
