package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSource<M extends BaseSource<M>> extends Model<M> implements IBean {

	public M setSourceId(java.lang.Integer sourceId) {
		set("sourceId", sourceId);
		return (M)this;
	}
	
	public java.lang.Integer getSourceId() {
		return getInt("sourceId");
	}

	public M setClassId(java.lang.String classId) {
		set("classId", classId);
		return (M)this;
	}
	
	public java.lang.String getClassId() {
		return getStr("classId");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setFilePath(java.lang.String filePath) {
		set("filePath", filePath);
		return (M)this;
	}
	
	public java.lang.String getFilePath() {
		return getStr("filePath");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setKickCount(java.lang.Integer kickCount) {
		set("kickCount", kickCount);
		return (M)this;
	}
	
	public java.lang.Integer getKickCount() {
		return getInt("kickCount");
	}

	public M setDownloadCount(java.lang.Integer downloadCount) {
		set("downloadCount", downloadCount);
		return (M)this;
	}
	
	public java.lang.Integer getDownloadCount() {
		return getInt("downloadCount");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

}
