package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseTopic<M extends BaseCourseTopic<M>> extends Model<M> implements IBean {

	public M setCourseId(java.lang.String courseId) {
		set("courseId", courseId);
		return (M)this;
	}
	
	public java.lang.String getCourseId() {
		return getStr("courseId");
	}

	public M setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
		return (M)this;
	}
	
	public java.lang.Integer getTopicId() {
		return getInt("topicId");
	}

}
