package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStatusreplyFile<M extends BaseStatusreplyFile<M>> extends Model<M> implements IBean {

	public M setReplyId(java.lang.Integer replyId) {
		set("replyId", replyId);
		return (M)this;
	}
	
	public java.lang.Integer getReplyId() {
		return getInt("replyId");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

}
