package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public M setAdminId(java.lang.String adminId) {
		set("adminId", adminId);
		return (M)this;
	}
	
	public java.lang.String getAdminId() {
		return getStr("adminId");
	}

	public M setAdminName(java.lang.String adminName) {
		set("adminName", adminName);
		return (M)this;
	}
	
	public java.lang.String getAdminName() {
		return getStr("adminName");
	}

	public M setPsd(java.lang.String psd) {
		set("psd", psd);
		return (M)this;
	}
	
	public java.lang.String getPsd() {
		return getStr("psd");
	}

}
