package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudentTestCase<M extends BaseStudentTestCase<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setTestCaseId(java.lang.Integer testCaseId) {
		set("testCaseId", testCaseId);
		return (M)this;
	}
	
	public java.lang.Integer getTestCaseId() {
		return getInt("testCaseId");
	}

	public M setExcuteStatus(java.lang.Integer excuteStatus) {
		set("excuteStatus", excuteStatus);
		return (M)this;
	}
	
	public java.lang.Integer getExcuteStatus() {
		return getInt("excuteStatus");
	}

	public M setIsExcutePass(java.lang.Integer isExcutePass) {
		set("isExcutePass", isExcutePass);
		return (M)this;
	}
	
	public java.lang.Integer getIsExcutePass() {
		return getInt("isExcutePass");
	}

}
