package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDepart<M extends BaseDepart<M>> extends Model<M> implements IBean {

	public M setDepartId(java.lang.Integer departId) {
		set("departId", departId);
		return (M)this;
	}
	
	public java.lang.Integer getDepartId() {
		return getInt("departId");
	}

	public M setDepartName(java.lang.String departName) {
		set("departName", departName);
		return (M)this;
	}
	
	public java.lang.String getDepartName() {
		return getStr("departName");
	}

}
