package com.ce.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTopicFile<M extends BaseTopicFile<M>> extends Model<M> implements IBean {

	public M setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
		return (M)this;
	}
	
	public java.lang.Integer getTopicId() {
		return getInt("topicId");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

}
