#include <stdio.h>
int main()
{
    int n,a,b,c,d,e,f,g,h,j,i,k;
    scanf("%d",&n);
    printf("{}");
    for(k=1;k<n+1;k++)
    {
        if(k=1)
        {
            for(a=0;a<n;a++)
            printf("\n{%d}",a);
        }
        if(k=2)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                printf("\n{%d,%d}",a,b);
            }
        }
        if(k=3)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    printf("\n{%d,%d,%d}",a,b,c);
                }
            }
        }
        if(k=4)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    {
                        for(d=c+1;d<n;d++)
                        printf("\n{%d,%d,%d,%d}",a,b,c,d);
                    }
                }
            }
        }
        if(k=5)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    {
                        for(d=c+1;d<n;d++)
                        {
                            for(e=d+1;e<n;e++)
                            printf("\n{%d,%d,%d,%d,%d}",a,b,c,d,e);
                        }
                    }
                }
            }
        }
        if(k=6)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    {
                        for(d=c+1;d<n;d++)
                        {
                            for(e=d+1;e<n;e++)
                            {
                                for(f=e+1;f<n;f++)
                                printf("\n{%d,%d,%d,%d,%d,%d}",a,b,c,d,e,f);
                            }
                        }
                    }
                }
            }
        }
        if(k=7)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    {
                        for(d=c+1;d<n;d++)
                        {
                            for(e=d+1;e<n;e++)
                            {
                                for(f=e+1;f<n;f++)
                                {
                                    for(g=f+1;g<n;g++)
                                    printf("\n{%d,%d,%d,%d,%d,%d,%d}",a,b,c,d,e,f,g);
                                }
                            }
                        }
                    }
                }
            }
        }
        if(k=8)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    {
                        for(d=c+1;d<n;d++)
                        {
                            for(e=d+1;e<n;e++)
                            {
                                for(f=e+1;f<n;f++)
                                {
                                    for(g=f+1;g<n;g++)
                                    {
                                        for(h=g+1;h<n;h++)
                                        printf("\n{%d,%d,%d,%d,%d,%d,%d,%d}",a,b,c,d,e,f,g,h);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if(k=9)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    {
                        for(d=c+1;d<n;d++)
                        {
                            for(e=d+1;e<n;e++)
                            {
                                for(f=e+1;f<n;f++)
                                {
                                    for(g=f+1;g<n;g++)
                                    {
                                        for(h=g+1;h<n;h++)
                                       {
                                           for(i=h+1;i<n;i++)
                                           printf("\n{%d,%d,%d,%d,%d,%d,%d,%d,%d}",a,b,c,d,e,f,g,h,i);
                                       }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if(k=10)
        {
            for(a=0;a<n;a++)
            {
                for(b=a+1;b<n;b++)
                {
                    for(c=b+1;c<n;c++)
                    {
                        for(d=c+1;d<n;d++)
                        {
                            for(e=d+1;e<n;e++)
                            {
                                for(f=e+1;f<n;f++)
                                {
                                    for(g=f+1;g<n;g++)
                                    {
                                        for(h=g+1;h<n;h++)
                                       {
                                           for(i=h+1;i<n;i++)
                                           {
                                               for(j=i+1;j<n;j++)
                                               printf("\n{%d,%d,%d,%d,%d,%d,%d,%d,%d,%d}",a,b,c,d,e,f,g,h,i,j);
                                           }
                                       }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return 0;
}
