package com.ce.model.first;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("question", "questionId", Question.class);
		// Composite Primary Key order: questionId,userId1,userId2
		arp.addMapping("similarity", "questionId,userId1,userId2", Similarity.class);
		// Composite Primary Key order: questionId,userId
		arp.addMapping("student_question", "questionId,userId", StudentQuestion.class);
		arp.addMapping("test_case", "testCaseId", TestCase.class);
		arp.addMapping("test_db", "testId", TestDb.class);
		arp.addMapping("test_db_test_case", "testCaseId", TestDbTestCase.class);
		// Composite Primary Key order: assignmentId,userId
		arp.addMapping("upload", "assignmentId,userId", Upload.class);
		arp.addMapping("violation", "violationId", Violation.class);
	}
}

