package com.ce.model.first;

import com.ce.model.first.base.BaseQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Question extends BaseQuestion<Question> {
	public static final Question dao = new Question().dao();
}
