package com.ce.model.first;

import com.ce.model.first.base.BaseSimilarity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Similarity extends BaseSimilarity<Similarity> {
	public static final Similarity dao = new Similarity().dao();
}
