package com.ce.model.first;

import com.ce.model.first.base.BaseStudentQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentQuestion extends BaseStudentQuestion<StudentQuestion> {
	public static final StudentQuestion dao = new StudentQuestion().dao();
}
