package com.ce.model.first;

import com.ce.model.first.base.BaseTestDbTestCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDbTestCase extends BaseTestDbTestCase<TestDbTestCase> {
	public static final TestDbTestCase dao = new TestDbTestCase().dao();
}
