package com.ce.model.first;

import com.ce.model.first.base.BaseTestDb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDb extends BaseTestDb<TestDb> {
	public static final TestDb dao = new TestDb().dao();
}
