package com.ce.model.first;

import com.ce.model.first.base.BaseTestDbTestCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestCase extends BaseTestDbTestCase<TestCase> {
	public static final TestCase dao = new TestCase().dao();
}
