package com.ce.model.first;

import com.ce.model.first.base.BaseUpload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Upload extends BaseUpload<Upload> {
	public static final Upload dao = new Upload().dao();
}
