package com.ce.model.second;

import com.ce.model.second.base.BaseAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
}
