package com.ce.model.second;

import com.ce.model.second.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City().dao();
}
