package com.ce.model.second;

import com.ce.model.second.base.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class().dao();
}
