package com.ce.model.second;

import com.ce.model.second.base.BaseClassShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassShare extends BaseClassShare<ClassShare> {
	public static final ClassShare dao = new ClassShare().dao();
}
