package com.ce.model.second;

import com.ce.model.second.base.BaseCourseShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseShare extends BaseCourseShare<CourseShare> {
	public static final CourseShare dao = new CourseShare().dao();
}
