package com.ce.model.second;

import com.ce.model.second.base.BaseCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Course extends BaseCourse<Course> {
	public static final Course dao = new Course().dao();
}
