package com.ce.model.second;

import com.ce.model.second.base.BaseCourseSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseSource extends BaseCourseSource<CourseSource> {
	public static final CourseSource dao = new CourseSource().dao();
}
