package com.ce.model.second;

import com.ce.model.second.base.BaseFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Friend extends BaseFriend<Friend> {
	public static final Friend dao = new Friend().dao();
}
