package com.ce.model.second;

import com.ce.model.second.base.BasePasswordResetToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PasswordResetToken extends BasePasswordResetToken<PasswordResetToken> {
	public static final PasswordResetToken dao = new PasswordResetToken().dao();
}
