package com.ce.model.second;

import com.ce.model.second.base.BasePpt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ppt extends BasePpt<Ppt> {
	public static final Ppt dao = new Ppt().dao();
}
