package com.ce.model.second;

import com.ce.model.second.base.BaseProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Province extends BaseProvince<Province> {
	public static final Province dao = new Province().dao();
}
