package com.ce.model.second;

import com.ce.model.second.base.BaseSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Source extends BaseSource<Source> {
	public static final Source dao = new Source().dao();
}
