package com.ce.model.second;

import com.ce.model.second.base.BaseSourcereplyFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SourcereplyFile extends BaseSourcereplyFile<SourcereplyFile> {
	public static final SourcereplyFile dao = new SourcereplyFile().dao();
}
