package com.ce.model.second;

import com.ce.model.second.base.BaseSourcereply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sourcereply extends BaseSourcereply<Sourcereply> {
	public static final Sourcereply dao = new Sourcereply().dao();
}
