package com.ce.model.second;

import com.ce.model.second.base.BaseSourceScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SourceScore extends BaseSourceScore<SourceScore> {
	public static final SourceScore dao = new SourceScore().dao();
}
