package com.ce.model.second;

import com.ce.model.second.base.BaseStatusreplyFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatusreplyFile extends BaseStatusreplyFile<StatusreplyFile> {
	public static final StatusreplyFile dao = new StatusreplyFile().dao();
}
