package com.ce.model.second;

import com.ce.model.second.base.BaseStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Status extends BaseStatus<Status> {
	public static final Status dao = new Status().dao();
}
