package com.ce.model.second;

import com.ce.model.second.base.BaseStatusFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatusFile extends BaseStatusFile<StatusFile> {
	public static final StatusFile dao = new StatusFile().dao();
}
