package com.ce.model.second;

import com.ce.model.second.base.BaseStudentAssignment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentAssignment extends BaseStudentAssignment<StudentAssignment> {
	public static final StudentAssignment dao = new StudentAssignment().dao();
}
