package com.ce.model.second;

import com.ce.model.second.base.BaseStudentClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentClass extends BaseStudentClass<StudentClass> {
	public static final StudentClass dao = new StudentClass().dao();
}
