package com.ce.model.second;

import com.ce.model.second.base.BaseToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Token extends BaseToken<Token> {
	public static final Token dao = new Token().dao();
}
