package com.ce.model.second;

import com.ce.model.second.base.BaseTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Topic extends BaseTopic<Topic> {
	public static final Topic dao = new Topic().dao();
}
