package com.ce.model.second;

import com.ce.model.second.base.BaseTopicreply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Topicreply extends BaseTopicreply<Topicreply> {
	public static final Topicreply dao = new Topicreply().dao();
}
