package com.ce.model.second;

import com.ce.model.second.base.BaseTopicreplyFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TopicreplyFile extends BaseTopicreplyFile<TopicreplyFile> {
	public static final TopicreplyFile dao = new TopicreplyFile().dao();
}
