package com.ce.model;

import com.ce.model.base.BaseAssignment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Assignment extends BaseAssignment<Assignment> {
	public static final Assignment dao = new Assignment().dao();
}
