package com.ce.model;

import com.ce.model.base.BaseClassTutor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassTutor extends BaseClassTutor<ClassTutor> {
	public static final ClassTutor dao = new ClassTutor().dao();
}
