package com.ce.model;

import com.ce.model.base.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class().dao();
}
