package com.ce.model;

import com.ce.model.base.BaseCourseTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseTopic extends BaseCourseTopic<CourseTopic> {
	public static final CourseTopic dao = new CourseTopic().dao();
}
