package com.ce.model;

import com.ce.model.base.BaseCourseShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseShare extends BaseCourseShare<CourseShare> {
	public static final CourseShare dao = new CourseShare().dao();
}
