package com.ce.model;

import com.ce.model.base.BaseCourseSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseSource extends BaseCourseSource<CourseSource> {
	public static final CourseSource dao = new CourseSource().dao();
}
