package com.ce.model;

import com.ce.model.base.BaseDepart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Depart extends BaseDepart<Depart> {
	public static final Depart dao = new Depart().dao();
}
