package com.ce.model;

import com.ce.model.base.BaseDorm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dorm extends BaseDorm<Dorm> {
	public static final Dorm dao = new Dorm().dao();
}
