package com.ce.model;

import com.ce.model.base.BaseExcuteResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExcuteResult extends BaseExcuteResult<ExcuteResult> {
	public static final ExcuteResult dao = new ExcuteResult().dao();
}
