package com.ce.model;

import com.ce.model.base.BasePasswordResetToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PasswordResetToken extends BasePasswordResetToken<PasswordResetToken> {
	public static final PasswordResetToken dao = new PasswordResetToken().dao();
}
