package com.ce.model;

import com.ce.model.base.BaseSimilarity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Similarity extends BaseSimilarity<Similarity> {
	public static final Similarity dao = new Similarity().dao();
}
