package com.ce.model;

import com.ce.model.base.BaseSourcereply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sourcereply extends BaseSourcereply<Sourcereply> {
	public static final Sourcereply dao = new Sourcereply().dao();
}
