package com.ce.model;

import com.ce.model.base.BaseStatusReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatusReply extends BaseStatusReply<StatusReply> {
	public static final StatusReply dao = new StatusReply().dao();
}
