package com.ce.model;

import com.ce.model.base.BaseStudentAssignment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentAssignment extends BaseStudentAssignment<StudentAssignment> {
	public static final StudentAssignment dao = new StudentAssignment().dao();
}
