package com.ce.model;

import com.ce.model.base.BaseStudentQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentQuestion extends BaseStudentQuestion<StudentQuestion> {
	public static final StudentQuestion dao = new StudentQuestion().dao();
}
