package com.ce.model;

import com.ce.model.base.BaseStudentTestCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudentTestCase extends BaseStudentTestCase<StudentTestCase> {
	public static final StudentTestCase dao = new StudentTestCase().dao();
}
