package com.ce.model;

import com.ce.model.base.BaseTerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Term extends BaseTerm<Term> {
	public static final Term dao = new Term().dao();
}
