package com.ce.model;

import com.ce.model.base.BaseTestCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestCase extends BaseTestCase<TestCase> {
	public static final TestCase dao = new TestCase().dao();
}
