package com.ce.model;

import com.ce.model.base.BaseTestDbTestCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDbTestCase extends BaseTestDbTestCase<TestDbTestCase> {
	public static final TestDbTestCase dao = new TestDbTestCase().dao();
}
