package com.ce.model;

import com.ce.model.base.BaseTestDb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDb extends BaseTestDb<TestDb> {
	public static final TestDb dao = new TestDb().dao();
}
