package com.ce.model;

import com.ce.model.base.BaseTopicFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TopicFile extends BaseTopicFile<TopicFile> {
	public static final TopicFile dao = new TopicFile().dao();
}
