package com.ce.model;

import com.ce.model.base.BaseTopicreply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Topicreply extends BaseTopicreply<Topicreply> {
	public static final Topicreply dao = new Topicreply().dao();
}
