package com.ce.model;

import com.ce.model.base.BaseViolation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Violation extends BaseViolation<Violation> {
	public static final Violation dao = new Violation().dao();
}
