package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassShare<M extends BaseClassShare<M>> extends Model<M> implements IBean {

	public M setClassidA(java.lang.String classidA) {
		set("classId_a", classidA);
		return (M)this;
	}
	
	public java.lang.String getClassidA() {
		return getStr("classId_a");
	}

	public M setClassidB(java.lang.String classidB) {
		set("classId_b", classidB);
		return (M)this;
	}
	
	public java.lang.String getClassidB() {
		return getStr("classId_b");
	}

}
