package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseSource<M extends BaseCourseSource<M>> extends Model<M> implements IBean {

	public M setCourseId(java.lang.String courseId) {
		set("courseId", courseId);
		return (M)this;
	}
	
	public java.lang.String getCourseId() {
		return getStr("courseId");
	}

	public M setSourceId(java.lang.Integer sourceId) {
		set("sourceId", sourceId);
		return (M)this;
	}
	
	public java.lang.Integer getSourceId() {
		return getInt("sourceId");
	}

}
