package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStatusReply<M extends BaseStatusReply<M>> extends Model<M> implements IBean {

	public M setReplyId(java.lang.Integer replyId) {
		set("replyId", replyId);
		return (M)this;
	}
	
	public java.lang.Integer getReplyId() {
		return getInt("replyId");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setFromId(java.lang.String fromId) {
		set("fromId", fromId);
		return (M)this;
	}
	
	public java.lang.String getFromId() {
		return getStr("fromId");
	}

	public M setStatusId(java.lang.String statusId) {
		set("statusId", statusId);
		return (M)this;
	}
	
	public java.lang.String getStatusId() {
		return getStr("statusId");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}

	public M setToId(java.lang.String toId) {
		set("toId", toId);
		return (M)this;
	}
	
	public java.lang.String getToId() {
		return getStr("toId");
	}

}
