package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudentClass<M extends BaseStudentClass<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setClassId(java.lang.String classId) {
		set("classId", classId);
		return (M)this;
	}
	
	public java.lang.String getClassId() {
		return getStr("classId");
	}

	public M setActivity(java.lang.Integer activity) {
		set("activity", activity);
		return (M)this;
	}
	
	public java.lang.Integer getActivity() {
		return getInt("activity");
	}

	public M setActivityExp(java.lang.Integer activityExp) {
		set("activityExp", activityExp);
		return (M)this;
	}
	
	public java.lang.Integer getActivityExp() {
		return getInt("activityExp");
	}

	public M setSocialExp(java.lang.Integer socialExp) {
		set("socialExp", socialExp);
		return (M)this;
	}
	
	public java.lang.Integer getSocialExp() {
		return getInt("socialExp");
	}

	public M setHomeworkExp(java.lang.Integer homeworkExp) {
		set("homeworkExp", homeworkExp);
		return (M)this;
	}
	
	public java.lang.Integer getHomeworkExp() {
		return getInt("homeworkExp");
	}

}
