package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCity<M extends BaseCity<M>> extends Model<M> implements IBean {

	public M setCityId(java.lang.String cityId) {
		set("cityId", cityId);
		return (M)this;
	}
	
	public java.lang.String getCityId() {
		return getStr("cityId");
	}

	public M setCityName(java.lang.String cityName) {
		set("cityName", cityName);
		return (M)this;
	}
	
	public java.lang.String getCityName() {
		return getStr("cityName");
	}

	public M setProvinceId(java.lang.String provinceId) {
		set("provinceId", provinceId);
		return (M)this;
	}
	
	public java.lang.String getProvinceId() {
		return getStr("provinceId");
	}

}
