package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTerm<M extends BaseTerm<M>> extends Model<M> implements IBean {

	public M setTermId(java.lang.Integer termId) {
		set("termId", termId);
		return (M)this;
	}
	
	public java.lang.Integer getTermId() {
		return getInt("termId");
	}

	public M setTermName(java.lang.String termName) {
		set("termName", termName);
		return (M)this;
	}
	
	public java.lang.String getTermName() {
		return getStr("termName");
	}

}
