package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseShare<M extends BaseCourseShare<M>> extends Model<M> implements IBean {

	public M setCourseidA(java.lang.String courseidA) {
		set("courseId_a", courseidA);
		return (M)this;
	}
	
	public java.lang.String getCourseidA() {
		return getStr("courseId_a");
	}

	public M setCourseidB(java.lang.String courseidB) {
		set("courseId_b", courseidB);
		return (M)this;
	}
	
	public java.lang.String getCourseidB() {
		return getStr("courseId_b");
	}

}
