package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProvince<M extends BaseProvince<M>> extends Model<M> implements IBean {

	public M setProvinceId(java.lang.String provinceId) {
		set("provinceId", provinceId);
		return (M)this;
	}
	
	public java.lang.String getProvinceId() {
		return getStr("provinceId");
	}

	public M setProvinceName(java.lang.String provinceName) {
		set("provinceName", provinceName);
		return (M)this;
	}
	
	public java.lang.String getProvinceName() {
		return getStr("provinceName");
	}

}
