package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClass<M extends BaseClass<M>> extends Model<M> implements IBean {

	public M setClassId(java.lang.String classId) {
		set("classId", classId);
		return (M)this;
	}
	
	public java.lang.String getClassId() {
		return getStr("classId");
	}

	public M setCourseId(java.lang.String courseId) {
		set("courseId", courseId);
		return (M)this;
	}
	
	public java.lang.String getCourseId() {
		return getStr("courseId");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setTermId(java.lang.Integer termId) {
		set("termId", termId);
		return (M)this;
	}
	
	public java.lang.Integer getTermId() {
		return getInt("termId");
	}

	public M setClassStatus(java.lang.Integer classStatus) {
		set("classStatus", classStatus);
		return (M)this;
	}
	
	public java.lang.Integer getClassStatus() {
		return getInt("classStatus");
	}

}
