package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSourcereply<M extends BaseSourcereply<M>> extends Model<M> implements IBean {

	public M setReplyId(java.lang.Integer replyId) {
		set("replyId", replyId);
		return (M)this;
	}
	
	public java.lang.Integer getReplyId() {
		return getInt("replyId");
	}

	public M setSourceId(java.lang.Integer sourceId) {
		set("sourceId", sourceId);
		return (M)this;
	}
	
	public java.lang.Integer getSourceId() {
		return getInt("sourceId");
	}

	public M setFromId(java.lang.String fromId) {
		set("fromId", fromId);
		return (M)this;
	}
	
	public java.lang.String getFromId() {
		return getStr("fromId");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

}
