package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setDetail(java.lang.String detail) {
		set("detail", detail);
		return (M)this;
	}
	
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public M setDeleteStatus(java.lang.Integer deleteStatus) {
		set("delete_status", deleteStatus);
		return (M)this;
	}
	
	public java.lang.Integer getDeleteStatus() {
		return getInt("delete_status");
	}

	public M setOwner(java.lang.String owner) {
		set("owner", owner);
		return (M)this;
	}
	
	public java.lang.String getOwner() {
		return getStr("owner");
	}

	public M setLastModifiedTime(java.util.Date lastModifiedTime) {
		set("last_modified_time", lastModifiedTime);
		return (M)this;
	}
	
	public java.util.Date getLastModifiedTime() {
		return get("last_modified_time");
	}

}
