package com.ce.model.second.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSourceScore<M extends BaseSourceScore<M>> extends Model<M> implements IBean {

	public M setSourceId(java.lang.Integer sourceId) {
		set("sourceId", sourceId);
		return (M)this;
	}
	
	public java.lang.Integer getSourceId() {
		return getInt("sourceId");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setScore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Integer getScore() {
		return getInt("score");
	}

}
