#include <stdio.h>
#include <stdlib.h>

int main()
{
    char A,B;int x;
    scanf("%s %s",&A,&B);
    if(A=='S')
    {
        if(B=='S')
        {
            x=0;
        }
        else
        {
            if(B=='R')
            {
                x=-1;
            }
            else
            {
                x=1;
            }
        }
    }
    else
    {
        if(A=='R')
        {
            if(B=='S')
            {
                x=1;
            }
            else
            {
                if(B=='R')
                {
                    x=0;
                }
                else
                {
                    x=-1;
                }
            }
        }
        else
        {
            if(B=='S')
            {
                x=-1;
            }
            else
            {
                if(B=='R')
                {
                    x=1;
                }
                else
                {
                    x=0;
                }
            }
        }
    }
    if(x==1)
    {
        printf("Alice");
    }
    else
    {
        if(x==0)
        {
            printf("Tie");
        }
        else
        {
            printf("Bob");
        }
    }
    return 0;
}