package com.ce.model.first.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudentQuestion<M extends BaseStudentQuestion<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setQuestionId(java.lang.Integer questionId) {
		set("questionId", questionId);
		return (M)this;
	}
	
	public java.lang.Integer getQuestionId() {
		return getInt("questionId");
	}

	public M setIsCompilePass(java.lang.Boolean isCompilePass) {
		set("isCompilePass", isCompilePass);
		return (M)this;
	}
	
	public java.lang.Boolean getIsCompilePass() {
		return get("isCompilePass");
	}

	public M setCompileErrorInfo(java.lang.String compileErrorInfo) {
		set("compileErrorInfo", compileErrorInfo);
		return (M)this;
	}
	
	public java.lang.String getCompileErrorInfo() {
		return getStr("compileErrorInfo");
	}

	public M setTestCaseScore(java.lang.Integer testCaseScore) {
		set("testCaseScore", testCaseScore);
		return (M)this;
	}
	
	public java.lang.Integer getTestCaseScore() {
		return getInt("testCaseScore");
	}

	public M setTestCasePassNum(java.lang.Integer testCasePassNum) {
		set("testCasePassNum", testCasePassNum);
		return (M)this;
	}
	
	public java.lang.Integer getTestCasePassNum() {
		return getInt("testCasePassNum");
	}

	public M setCodePath(java.lang.String codePath) {
		set("codePath", codePath);
		return (M)this;
	}
	
	public java.lang.String getCodePath() {
		return getStr("codePath");
	}

	public M setEvaluationScore(java.lang.Integer evaluationScore) {
		set("evaluationScore", evaluationScore);
		return (M)this;
	}
	
	public java.lang.Integer getEvaluationScore() {
		return getInt("evaluationScore");
	}

}
