package com.ce.model.first.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSimilarity<M extends BaseSimilarity<M>> extends Model<M> implements IBean {

	public M setUserId1(java.lang.String userId1) {
		set("userId1", userId1);
		return (M)this;
	}
	
	public java.lang.String getUserId1() {
		return getStr("userId1");
	}

	public M setUserId2(java.lang.String userId2) {
		set("userId2", userId2);
		return (M)this;
	}
	
	public java.lang.String getUserId2() {
		return getStr("userId2");
	}

	public M setQuestionId(java.lang.Integer questionId) {
		set("questionId", questionId);
		return (M)this;
	}
	
	public java.lang.Integer getQuestionId() {
		return getInt("questionId");
	}

	public M setSimilarity(java.lang.Integer similarity) {
		set("similarity", similarity);
		return (M)this;
	}
	
	public java.lang.Integer getSimilarity() {
		return getInt("similarity");
	}

}
