package com.ce.model.first.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public M setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
		return (M)this;
	}
	
	public java.lang.Integer getTopicId() {
		return getInt("topicId");
	}

	public M setTopicName(java.lang.String topicName) {
		set("topicName", topicName);
		return (M)this;
	}
	
	public java.lang.String getTopicName() {
		return getStr("topicName");
	}

}
