package com.ce.model.first.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUpload<M extends BaseUpload<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setAssignmentId(java.lang.Integer assignmentId) {
		set("assignmentId", assignmentId);
		return (M)this;
	}
	
	public java.lang.Integer getAssignmentId() {
		return getInt("assignmentId");
	}

	public M setUploadDirectory(java.lang.String uploadDirectory) {
		set("uploadDirectory", uploadDirectory);
		return (M)this;
	}
	
	public java.lang.String getUploadDirectory() {
		return getStr("uploadDirectory");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setUploadFileInfo(java.lang.String uploadFileInfo) {
		set("uploadFileInfo", uploadFileInfo);
		return (M)this;
	}
	
	public java.lang.String getUploadFileInfo() {
		return getStr("uploadFileInfo");
	}

	public M setEvaluateDate(java.util.Date evaluateDate) {
		set("evaluateDate", evaluateDate);
		return (M)this;
	}
	
	public java.util.Date getEvaluateDate() {
		return get("evaluateDate");
	}

}
