#include<stdio.h>
#include<math.h>
int main()
{
    int sh1=0,sh2=0;
    int shu1[10],shu2[10],rstt[10];
    char c;
    int rst=0,i,amt,rts;
    int a,j,b,d,k,tim=1;
    for(a=0;a<10;a++)
    {
        scanf("%c",&c);
        if(c!='+')
        {
            shu1[a]=c-'0';
        }
        else
        {
            break;
        }
    }
    for(j=0;j<a;j++)
    {
        tim=pow(10,a-j-1);
        sh1+=shu1[j]*tim;
    }
    for(b=0;b<10;b++)
    {
        scanf("%c",&c);
        if(c!='=')
        {
            shu2[b]=c-'0';
        }
        else
        {
            break;
        }
    }
    for(j=0;j<b;j++)
    {
        tim=pow(10,b-j-1);
        sh2+=shu2[j]*tim;
    }
    for(d=0;d<10;d++)
    {
        scanf("%c",&c);
        if(c!='\n')
        {
            rstt[d]=c-'0';
        }
        else
        {
            break;
        }
    }
    for(j=0;j<d;j++)
    {
        for(k=0;k<d-j-1;++k)
        {
            tim*=10;
        }
        rst+=rstt[j]*tim;
        tim=1;
    }
    amt=sh1+sh2;
    if(amt==rst)
    {
        printf("0");
    }
    else
    {
        for(i=1;i<10;i++)
    {
        if(i==2)
        {
            amt=100;
        }
        else
        {
         amt=pow(10,i);
        }
        rts=amt*sh2+sh1;
        if(rts==rst)
        {
            printf("%d",i);
            break;
        }
    }
    if(i==10)
    {
     for(i=1;i<10;i++)
    {
        if(i==2)
        {
            amt=100;
        }
        else
        {
         amt=pow(10,i);
        }
        rts=amt*sh1+sh2;
        if(rts==rst)
        {
            printf("%d",i);
            break;
        }
    }
    }
    }
    return 0;
}

